---
platform: linux

inputs:
- name: env # contains the env file with target OpsMan Information
params:
  ENV_FILE: env.yml
run:
  path: bash
  args:
  - "-c"
  - |
    set -eu
    cat /var/version && echo ""
#    om --env env/"${ENV_FILE}" update-ssl-certificate --certificate-pem="((domain-crt))" --private-key-pem="((domain-key))"
